// Harmonograf v1 — control delivery channel.
//
// SubscribeControl is a server-streaming RPC opened by the agent right
// after StreamTelemetry's Welcome arrives. The server pushes ControlEvents
// scoped to the (agent_id, stream_id) pair; the agent's acks travel back
// upstream on StreamTelemetry, NOT on this stream.
//
// Splitting control out from telemetry gives control its own gRPC flow
// window, so a stalled payload upload on the telemetry stream can never
// delay a PAUSE event. See docs/design/01 §4.2.1.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file harmonograf/v1/control.proto (package harmonograf.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file harmonograf/v1/control.proto.
 */
export const file_harmonograf_v1_control: GenFile = /*@__PURE__*/
  fileDesc("ChxoYXJtb25vZ3JhZi92MS9jb250cm9sLnByb3RvEg5oYXJtb25vZ3JhZi52MSJSChdTdWJzY3JpYmVDb250cm9sUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhAKCGFnZW50X2lkGAIgASgJEhEKCXN0cmVhbV9pZBgDIAEoCUJCWkBnaXRodWIuY29tL3BlZGFwdWRpL2hhcm1vbm9ncmFmL2dlbi9oYXJtb25vZ3JhZi92MTtoYXJtb25vZ3JhZnYxYgZwcm90bzM");

/**
 * Subscribes to control events for one telemetry stream. The session_id,
 * agent_id, and stream_id must match a stream the server has previously
 * accepted (i.e., one that received a Welcome from StreamTelemetry).
 *
 * Multiple SubscribeControl calls under the same agent_id are allowed
 * (one per concurrent telemetry stream); the server fans every
 * SendControl out to all of them.
 *
 * @generated from message harmonograf.v1.SubscribeControlRequest
 */
export type SubscribeControlRequest = Message<"harmonograf.v1.SubscribeControlRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string agent_id = 2;
   */
  agentId: string;

  /**
   * @generated from field: string stream_id = 3;
   */
  streamId: string;
};

/**
 * Describes the message harmonograf.v1.SubscribeControlRequest.
 * Use `create(SubscribeControlRequestSchema)` to create a new message.
 */
export const SubscribeControlRequestSchema: GenMessage<SubscribeControlRequest> = /*@__PURE__*/
  messageDesc(file_harmonograf_v1_control, 0);

