// Harmonograf v1 — service aggregation.
//
// One gRPC service that hosts every RPC: the agent-facing telemetry
// and control streams plus the frontend-facing UI RPCs. Splitting the
// declaration into its own file (rather than scattering service{}
// blocks across telemetry.proto, control.proto, frontend.proto) keeps
// the wire contract legible in one place.
//
// Why a single service instead of separate services per concern?
// - gRPC clients can share one channel across all RPCs.
// - Auth metadata (when v1 hosted mode lands) applies uniformly.
// - Version rollouts happen at the service level; one version knob is
//   easier than three.
//
// See docs/design/01 §4 for the per-RPC semantics.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file harmonograf/v1/service.proto (package harmonograf.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { TelemetryDownSchema, TelemetryUpSchema } from "./telemetry_pb.js";
import { file_harmonograf_v1_telemetry } from "./telemetry_pb.js";
import type { SubscribeControlRequestSchema } from "./control_pb.js";
import { file_harmonograf_v1_control } from "./control_pb.js";
import type { DeleteSessionRequestSchema, DeleteSessionResponseSchema, GetPayloadRequestSchema, GetSessionPlanHistoryRequestSchema, GetSessionPlanHistoryResponseSchema, GetSpanTreeRequestSchema, GetSpanTreeResponseSchema, GetStatsRequestSchema, GetStatsResponseSchema, ListInterventionsRequestSchema, ListInterventionsResponseSchema, ListSessionsRequestSchema, ListSessionsResponseSchema, PayloadChunkSchema, PostAnnotationRequestSchema, PostAnnotationResponseSchema, SendControlRequestSchema, SendControlResponseSchema, SessionUpdateSchema, WatchSessionRequestSchema } from "./frontend_pb.js";
import { file_harmonograf_v1_frontend } from "./frontend_pb.js";
import { file_harmonograf_v1_types } from "./types_pb.js";
import type { ControlEventSchema } from "../../goldfive/v1/control_pb.js";
import { file_goldfive_v1_control } from "../../goldfive/v1/control_pb.js";

/**
 * Describes the file harmonograf/v1/service.proto.
 */
export const file_harmonograf_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChxoYXJtb25vZ3JhZi92MS9zZXJ2aWNlLnByb3RvEg5oYXJtb25vZ3JhZi52MTLaCAoLSGFybW9ub2dyYWYSUQoPU3RyZWFtVGVsZW1ldHJ5EhsuaGFybW9ub2dyYWYudjEuVGVsZW1ldHJ5VXAaHS5oYXJtb25vZ3JhZi52MS5UZWxlbWV0cnlEb3duKAEwARJYChBTdWJzY3JpYmVDb250cm9sEicuaGFybW9ub2dyYWYudjEuU3Vic2NyaWJlQ29udHJvbFJlcXVlc3QaGS5nb2xkZml2ZS52MS5Db250cm9sRXZlbnQwARJZCgxMaXN0U2Vzc2lvbnMSIy5oYXJtb25vZ3JhZi52MS5MaXN0U2Vzc2lvbnNSZXF1ZXN0GiQuaGFybW9ub2dyYWYudjEuTGlzdFNlc3Npb25zUmVzcG9uc2USVAoMV2F0Y2hTZXNzaW9uEiMuaGFybW9ub2dyYWYudjEuV2F0Y2hTZXNzaW9uUmVxdWVzdBodLmhhcm1vbm9ncmFmLnYxLlNlc3Npb25VcGRhdGUwARJPCgpHZXRQYXlsb2FkEiEuaGFybW9ub2dyYWYudjEuR2V0UGF5bG9hZFJlcXVlc3QaHC5oYXJtb25vZ3JhZi52MS5QYXlsb2FkQ2h1bmswARJWCgtHZXRTcGFuVHJlZRIiLmhhcm1vbm9ncmFmLnYxLkdldFNwYW5UcmVlUmVxdWVzdBojLmhhcm1vbm9ncmFmLnYxLkdldFNwYW5UcmVlUmVzcG9uc2USXwoOUG9zdEFubm90YXRpb24SJS5oYXJtb25vZ3JhZi52MS5Qb3N0QW5ub3RhdGlvblJlcXVlc3QaJi5oYXJtb25vZ3JhZi52MS5Qb3N0QW5ub3RhdGlvblJlc3BvbnNlElYKC1NlbmRDb250cm9sEiIuaGFybW9ub2dyYWYudjEuU2VuZENvbnRyb2xSZXF1ZXN0GiMuaGFybW9ub2dyYWYudjEuU2VuZENvbnRyb2xSZXNwb25zZRJcCg1EZWxldGVTZXNzaW9uEiQuaGFybW9ub2dyYWYudjEuRGVsZXRlU2Vzc2lvblJlcXVlc3QaJS5oYXJtb25vZ3JhZi52MS5EZWxldGVTZXNzaW9uUmVzcG9uc2USTQoIR2V0U3RhdHMSHy5oYXJtb25vZ3JhZi52MS5HZXRTdGF0c1JlcXVlc3QaIC5oYXJtb25vZ3JhZi52MS5HZXRTdGF0c1Jlc3BvbnNlEmgKEUxpc3RJbnRlcnZlbnRpb25zEiguaGFybW9ub2dyYWYudjEuTGlzdEludGVydmVudGlvbnNSZXF1ZXN0GikuaGFybW9ub2dyYWYudjEuTGlzdEludGVydmVudGlvbnNSZXNwb25zZRJ0ChVHZXRTZXNzaW9uUGxhbkhpc3RvcnkSLC5oYXJtb25vZ3JhZi52MS5HZXRTZXNzaW9uUGxhbkhpc3RvcnlSZXF1ZXN0Gi0uaGFybW9ub2dyYWYudjEuR2V0U2Vzc2lvblBsYW5IaXN0b3J5UmVzcG9uc2VCQlpAZ2l0aHViLmNvbS9wZWRhcHVkaS9oYXJtb25vZ3JhZi9nZW4vaGFybW9ub2dyYWYvdjE7aGFybW9ub2dyYWZ2MWIGcHJvdG8z", [file_harmonograf_v1_telemetry, file_harmonograf_v1_control, file_harmonograf_v1_frontend, file_harmonograf_v1_types, file_goldfive_v1_control]);

/**
 * --- Agent → server: high-volume telemetry ---------------------------
 *
 * @generated from service harmonograf.v1.Harmonograf
 */
export const Harmonograf: GenService<{
  /**
   * Bidirectional. Agent sends Hello, SpanStart/Update/End, PayloadUpload
   * chunks, Heartbeat, ControlAck, Goodbye. Server sends Welcome,
   * PayloadRequest, FlowControl, ServerGoodbye.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.StreamTelemetry
   */
  streamTelemetry: {
    methodKind: "bidi_streaming";
    input: typeof TelemetryUpSchema;
    output: typeof TelemetryDownSchema;
  },
  /**
   * Server-streaming. Agent opens this once after StreamTelemetry's
   * Welcome. Server pushes goldfive.v1.ControlEvents. Agent ACKs travel
   * back upstream on StreamTelemetry (not on this stream), preserving
   * happens-before and avoiding a third RPC.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.SubscribeControl
   */
  subscribeControl: {
    methodKind: "server_streaming";
    input: typeof SubscribeControlRequestSchema;
    output: typeof ControlEventSchema;
  },
  /**
   * List sessions for the picker. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.ListSessions
   */
  listSessions: {
    methodKind: "unary";
    input: typeof ListSessionsRequestSchema;
    output: typeof ListSessionsResponseSchema;
  },
  /**
   * Subscribe to one session's existing state + live deltas.
   * Server-streaming.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.WatchSession
   */
  watchSession: {
    methodKind: "server_streaming";
    input: typeof WatchSessionRequestSchema;
    output: typeof SessionUpdateSchema;
  },
  /**
   * Lazy payload fetch for the inspector drawer. Server-streaming so
   * large payloads can deliver in chunks.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.GetPayload
   */
  getPayload: {
    methodKind: "server_streaming";
    input: typeof GetPayloadRequestSchema;
    output: typeof PayloadChunkSchema;
  },
  /**
   * Snapshot query for a time window on a session. Used on initial
   * session open and large viewport jumps. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.GetSpanTree
   */
  getSpanTree: {
    methodKind: "unary";
    input: typeof GetSpanTreeRequestSchema;
    output: typeof GetSpanTreeResponseSchema;
  },
  /**
   * Post an annotation. For STEERING and HUMAN_RESPONSE, the server
   * routes the body as a control event and waits for ack before
   * returning. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.PostAnnotation
   */
  postAnnotation: {
    methodKind: "unary";
    input: typeof PostAnnotationRequestSchema;
    output: typeof PostAnnotationResponseSchema;
  },
  /**
   * Issue a control event to an agent and wait for ack. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.SendControl
   */
  sendControl: {
    methodKind: "unary";
    input: typeof SendControlRequestSchema;
    output: typeof SendControlResponseSchema;
  },
  /**
   * Delete a session and its spans, annotations, and payloads. Refuses
   * LIVE sessions unless force = true. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.DeleteSession
   */
  deleteSession: {
    methodKind: "unary";
    input: typeof DeleteSessionRequestSchema;
    output: typeof DeleteSessionResponseSchema;
  },
  /**
   * Retention / storage stats for the Settings page. Unary.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.GetStats
   */
  getStats: {
    methodKind: "unary";
    input: typeof GetStatsRequestSchema;
    output: typeof GetStatsResponseSchema;
  },
  /**
   * Merged chronological intervention history for one session. Unary —
   * the frontend recomputes live updates from WatchSession deltas.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.ListInterventions
   */
  listInterventions: {
    methodKind: "unary";
    input: typeof ListInterventionsRequestSchema;
    output: typeof ListInterventionsResponseSchema;
  },
  /**
   * Full plan-revision history for one session. Unary. Returns every
   * persisted ``task_plans`` row for the session in ``created_at`` order
   * so the frontend can render plans as an evolving artifact
   * (generations, supersedes edges annotated with their triggering drift
   * or user steer). See frontend.proto GetSessionPlanHistory docs.
   *
   * @generated from rpc harmonograf.v1.Harmonograf.GetSessionPlanHistory
   */
  getSessionPlanHistory: {
    methodKind: "unary";
    input: typeof GetSessionPlanHistoryRequestSchema;
    output: typeof GetSessionPlanHistoryResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_harmonograf_v1_service, 0);

