# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from goldfive.v1 import control_pb2 as goldfive_dot_v1_dot_control__pb2
from harmonograf.v1 import control_pb2 as harmonograf_dot_v1_dot_control__pb2
from harmonograf.v1 import frontend_pb2 as harmonograf_dot_v1_dot_frontend__pb2
from harmonograf.v1 import telemetry_pb2 as harmonograf_dot_v1_dot_telemetry__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in harmonograf/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HarmonografStub(object):
    """--- Agent → server: high-volume telemetry ---------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_stream(
                '/harmonograf.v1.Harmonograf/StreamTelemetry',
                request_serializer=harmonograf_dot_v1_dot_telemetry__pb2.TelemetryUp.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_telemetry__pb2.TelemetryDown.FromString,
                _registered_method=True)
        self.SubscribeControl = channel.unary_stream(
                '/harmonograf.v1.Harmonograf/SubscribeControl',
                request_serializer=harmonograf_dot_v1_dot_control__pb2.SubscribeControlRequest.SerializeToString,
                response_deserializer=goldfive_dot_v1_dot_control__pb2.ControlEvent.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/ListSessions',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.WatchSession = channel.unary_stream(
                '/harmonograf.v1.Harmonograf/WatchSession',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.WatchSessionRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.SessionUpdate.FromString,
                _registered_method=True)
        self.GetPayload = channel.unary_stream(
                '/harmonograf.v1.Harmonograf/GetPayload',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.GetPayloadRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.PayloadChunk.FromString,
                _registered_method=True)
        self.GetSpanTree = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/GetSpanTree',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeResponse.FromString,
                _registered_method=True)
        self.PostAnnotation = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/PostAnnotation',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationResponse.FromString,
                _registered_method=True)
        self.SendControl = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/SendControl',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.SendControlRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.SendControlResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/DeleteSession',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/GetStats',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.GetStatsResponse.FromString,
                _registered_method=True)
        self.ListInterventions = channel.unary_unary(
                '/harmonograf.v1.Harmonograf/ListInterventions',
                request_serializer=harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsRequest.SerializeToString,
                response_deserializer=harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsResponse.FromString,
                _registered_method=True)


class HarmonografServicer(object):
    """--- Agent → server: high-volume telemetry ---------------------------
    """

    def StreamTelemetry(self, request_iterator, context):
        """Bidirectional. Agent sends Hello, SpanStart/Update/End, PayloadUpload
        chunks, Heartbeat, ControlAck, Goodbye. Server sends Welcome,
        PayloadRequest, FlowControl, ServerGoodbye.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeControl(self, request, context):
        """--- Server → agent: low-volume control delivery ---------------------

        Server-streaming. Agent opens this once after StreamTelemetry's
        Welcome. Server pushes goldfive.v1.ControlEvents. Agent ACKs travel
        back upstream on StreamTelemetry (not on this stream), preserving
        happens-before and avoiding a third RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """--- Frontend → server: UI RPCs ---------------------------------------

        List sessions for the picker. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSession(self, request, context):
        """Subscribe to one session's existing state + live deltas.
        Server-streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayload(self, request, context):
        """Lazy payload fetch for the inspector drawer. Server-streaming so
        large payloads can deliver in chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpanTree(self, request, context):
        """Snapshot query for a time window on a session. Used on initial
        session open and large viewport jumps. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostAnnotation(self, request, context):
        """Post an annotation. For STEERING and HUMAN_RESPONSE, the server
        routes the body as a control event and waits for ack before
        returning. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControl(self, request, context):
        """Issue a control event to an agent and wait for ack. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Delete a session and its spans, annotations, and payloads. Refuses
        LIVE sessions unless force = true. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Retention / storage stats for the Settings page. Unary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInterventions(self, request, context):
        """Merged chronological intervention history for one session. Unary —
        the frontend recomputes live updates from WatchSession deltas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarmonografServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=harmonograf_dot_v1_dot_telemetry__pb2.TelemetryUp.FromString,
                    response_serializer=harmonograf_dot_v1_dot_telemetry__pb2.TelemetryDown.SerializeToString,
            ),
            'SubscribeControl': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeControl,
                    request_deserializer=harmonograf_dot_v1_dot_control__pb2.SubscribeControlRequest.FromString,
                    response_serializer=goldfive_dot_v1_dot_control__pb2.ControlEvent.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.ListSessionsRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.ListSessionsResponse.SerializeToString,
            ),
            'WatchSession': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSession,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.WatchSessionRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.SessionUpdate.SerializeToString,
            ),
            'GetPayload': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPayload,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.GetPayloadRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.PayloadChunk.SerializeToString,
            ),
            'GetSpanTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpanTree,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeResponse.SerializeToString,
            ),
            'PostAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.PostAnnotation,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationResponse.SerializeToString,
            ),
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.SendControlRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.SendControlResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.GetStatsRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.GetStatsResponse.SerializeToString,
            ),
            'ListInterventions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInterventions,
                    request_deserializer=harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsRequest.FromString,
                    response_serializer=harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harmonograf.v1.Harmonograf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('harmonograf.v1.Harmonograf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Harmonograf(object):
    """--- Agent → server: high-volume telemetry ---------------------------
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/harmonograf.v1.Harmonograf/StreamTelemetry',
            harmonograf_dot_v1_dot_telemetry__pb2.TelemetryUp.SerializeToString,
            harmonograf_dot_v1_dot_telemetry__pb2.TelemetryDown.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/harmonograf.v1.Harmonograf/SubscribeControl',
            harmonograf_dot_v1_dot_control__pb2.SubscribeControlRequest.SerializeToString,
            goldfive_dot_v1_dot_control__pb2.ControlEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/ListSessions',
            harmonograf_dot_v1_dot_frontend__pb2.ListSessionsRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/harmonograf.v1.Harmonograf/WatchSession',
            harmonograf_dot_v1_dot_frontend__pb2.WatchSessionRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.SessionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/harmonograf.v1.Harmonograf/GetPayload',
            harmonograf_dot_v1_dot_frontend__pb2.GetPayloadRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.PayloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpanTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/GetSpanTree',
            harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.GetSpanTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/PostAnnotation',
            harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.PostAnnotationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/SendControl',
            harmonograf_dot_v1_dot_frontend__pb2.SendControlRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.SendControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/DeleteSession',
            harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/GetStats',
            harmonograf_dot_v1_dot_frontend__pb2.GetStatsRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInterventions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harmonograf.v1.Harmonograf/ListInterventions',
            harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsRequest.SerializeToString,
            harmonograf_dot_v1_dot_frontend__pb2.ListInterventionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
