# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: harmonograf/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'harmonograf/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from harmonograf.v1 import telemetry_pb2 as harmonograf_dot_v1_dot_telemetry__pb2
from harmonograf.v1 import control_pb2 as harmonograf_dot_v1_dot_control__pb2
from harmonograf.v1 import frontend_pb2 as harmonograf_dot_v1_dot_frontend__pb2
from harmonograf.v1 import types_pb2 as harmonograf_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1charmonograf/v1/service.proto\x12\x0eharmonograf.v1\x1a\x1eharmonograf/v1/telemetry.proto\x1a\x1charmonograf/v1/control.proto\x1a\x1dharmonograf/v1/frontend.proto\x1a\x1aharmonograf/v1/types.proto2\xfd\x06\n\x0bHarmonograf\x12Q\n\x0fStreamTelemetry\x12\x1b.harmonograf.v1.TelemetryUp\x1a\x1d.harmonograf.v1.TelemetryDown(\x01\x30\x01\x12[\n\x10SubscribeControl\x12\'.harmonograf.v1.SubscribeControlRequest\x1a\x1c.harmonograf.v1.ControlEvent0\x01\x12Y\n\x0cListSessions\x12#.harmonograf.v1.ListSessionsRequest\x1a$.harmonograf.v1.ListSessionsResponse\x12T\n\x0cWatchSession\x12#.harmonograf.v1.WatchSessionRequest\x1a\x1d.harmonograf.v1.SessionUpdate0\x01\x12O\n\nGetPayload\x12!.harmonograf.v1.GetPayloadRequest\x1a\x1c.harmonograf.v1.PayloadChunk0\x01\x12V\n\x0bGetSpanTree\x12\".harmonograf.v1.GetSpanTreeRequest\x1a#.harmonograf.v1.GetSpanTreeResponse\x12_\n\x0ePostAnnotation\x12%.harmonograf.v1.PostAnnotationRequest\x1a&.harmonograf.v1.PostAnnotationResponse\x12V\n\x0bSendControl\x12\".harmonograf.v1.SendControlRequest\x1a#.harmonograf.v1.SendControlResponse\x12\\\n\rDeleteSession\x12$.harmonograf.v1.DeleteSessionRequest\x1a%.harmonograf.v1.DeleteSessionResponse\x12M\n\x08GetStats\x12\x1f.harmonograf.v1.GetStatsRequest\x1a .harmonograf.v1.GetStatsResponseBBZ@github.com/pedapudi/harmonograf/gen/harmonograf/v1;harmonografv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harmonograf.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/pedapudi/harmonograf/gen/harmonograf/v1;harmonografv1'
  _globals['_HARMONOGRAF']._serialized_start=170
  _globals['_HARMONOGRAF']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
