// Goldfive v1 — gRPC transport surface.
//
// `GoldfiveIngress` is the network-facing twin of the in-process
// `EventSink` contract. Clients (typically a `GRPCSink` inside a
// Runner) stream `Event` messages over a client-streaming RPC; the
// server fans them out to one or more local `EventSink`s (SQLite,
// JSONL, in-memory, ...).
//
// The single RPC is `StreamEvents`: client-streaming, one response.
// The server consumes the entire client stream and returns a summary
// once the client half-closes. A non-empty `error` in the response
// signals a server-side failure; `received` always reflects the
// number of events the server successfully processed.

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file goldfive/v1/service.proto (package goldfive.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EventSchema } from "./events_pb.js";
import { file_goldfive_v1_events } from "./events_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file goldfive/v1/service.proto.
 */
export const file_goldfive_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Chlnb2xkZml2ZS92MS9zZXJ2aWNlLnByb3RvEgtnb2xkZml2ZS52MSI3ChRTdHJlYW1FdmVudHNSZXNwb25zZRIQCghyZWNlaXZlZBgBIAEoBBINCgVlcnJvchgCIAEoCTJaCg9Hb2xkZml2ZUluZ3Jlc3MSRwoMU3RyZWFtRXZlbnRzEhIuZ29sZGZpdmUudjEuRXZlbnQaIS5nb2xkZml2ZS52MS5TdHJlYW1FdmVudHNSZXNwb25zZSgBQjlaN2dpdGh1Yi5jb20vcGVkYXB1ZGkvZ29sZGZpdmUvZ2VuL2dvbGRmaXZlL3YxO2dvbGRmaXZldjFiBnByb3RvMw", [file_goldfive_v1_events]);

/**
 * @generated from message goldfive.v1.StreamEventsResponse
 */
export type StreamEventsResponse = Message<"goldfive.v1.StreamEventsResponse"> & {
  /**
   * Number of events the server successfully processed.
   *
   * @generated from field: uint64 received = 1;
   */
  received: bigint;

  /**
   * Non-empty iff the server failed while processing the stream.
   * The error string is informational; the RPC status code carries
   * the authoritative failure signal.
   *
   * @generated from field: string error = 2;
   */
  error: string;
};

/**
 * Describes the message goldfive.v1.StreamEventsResponse.
 * Use `create(StreamEventsResponseSchema)` to create a new message.
 */
export const StreamEventsResponseSchema: GenMessage<StreamEventsResponse> = /*@__PURE__*/
  messageDesc(file_goldfive_v1_service, 0);

/**
 * @generated from service goldfive.v1.GoldfiveIngress
 */
export const GoldfiveIngress: GenService<{
  /**
   * Client streams Events; server returns a single summary after the
   * client half-closes. Implementations fan events out to local
   * EventSinks in order.
   *
   * @generated from rpc goldfive.v1.GoldfiveIngress.StreamEvents
   */
  streamEvents: {
    methodKind: "client_streaming";
    input: typeof EventSchema;
    output: typeof StreamEventsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_goldfive_v1_service, 0);

